allowBuilds:
  '@nestjs/core': set this to true or false
  '@openapitools/openapi-generator-cli': set this to true or false
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  vue-demi: set this to true or false
